### ISSUE TITLE
Tier 4: Edit Form on Single Item View

### ISSUE THREAD

**Issue by courtlyncodes** [CADS-Dry-INC-Sons/inventory-app#12]
- [x] Create edit button on single item view
- [x] toggle the button on click to show and hide
- [x] Create a new EditForm component
- [x] Add isEditing state to show the form
- [x] Create an onSubmit on the form to handle the fetch request
- [x] toggle to hide from after onSubmit with updating the showItem

**Comment by arwas11** [comment]
done and done
